/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as PayIdRouteImport } from './routes/pay.$id'
import { Route as LearnSecurityRouteImport } from './routes/learn.security'
import { Route as LearnPaymentsRouteImport } from './routes/learn.payments'
import { Route as LearnInvoiceRouteImport } from './routes/learn.invoice'
import { Route as LearnGettingStartedRouteImport } from './routes/learn.getting-started'
import { Route as LearnFaqRouteImport } from './routes/learn.faq'
import { Route as LearnBusinessRouteImport } from './routes/learn.business'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIdRoute = PayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSecurityRoute = LearnSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => LearnRoute,
} as any)
const LearnPaymentsRoute = LearnPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => LearnRoute,
} as any)
const LearnInvoiceRoute = LearnInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => LearnRoute,
} as any)
const LearnGettingStartedRoute = LearnGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => LearnRoute,
} as any)
const LearnFaqRoute = LearnFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LearnRoute,
} as any)
const LearnBusinessRoute = LearnBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => LearnRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/learn/business': typeof LearnBusinessRoute
  '/learn/faq': typeof LearnFaqRoute
  '/learn/getting-started': typeof LearnGettingStartedRoute
  '/learn/invoice': typeof LearnInvoiceRoute
  '/learn/payments': typeof LearnPaymentsRoute
  '/learn/security': typeof LearnSecurityRoute
  '/pay/$id': typeof PayIdRoute
  '/invoices/': typeof InvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/learn/business': typeof LearnBusinessRoute
  '/learn/faq': typeof LearnFaqRoute
  '/learn/getting-started': typeof LearnGettingStartedRoute
  '/learn/invoice': typeof LearnInvoiceRoute
  '/learn/payments': typeof LearnPaymentsRoute
  '/learn/security': typeof LearnSecurityRoute
  '/pay/$id': typeof PayIdRoute
  '/invoices': typeof InvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/learn/business': typeof LearnBusinessRoute
  '/learn/faq': typeof LearnFaqRoute
  '/learn/getting-started': typeof LearnGettingStartedRoute
  '/learn/invoice': typeof LearnInvoiceRoute
  '/learn/payments': typeof LearnPaymentsRoute
  '/learn/security': typeof LearnSecurityRoute
  '/pay/$id': typeof PayIdRoute
  '/invoices/': typeof InvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/learn'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/invoices/$id'
    | '/invoices/new'
    | '/learn/business'
    | '/learn/faq'
    | '/learn/getting-started'
    | '/learn/invoice'
    | '/learn/payments'
    | '/learn/security'
    | '/pay/$id'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/learn'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/invoices/$id'
    | '/invoices/new'
    | '/learn/business'
    | '/learn/faq'
    | '/learn/getting-started'
    | '/learn/invoice'
    | '/learn/payments'
    | '/learn/security'
    | '/pay/$id'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/learn'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/invoices/$id'
    | '/invoices/new'
    | '/learn/business'
    | '/learn/faq'
    | '/learn/getting-started'
    | '/learn/invoice'
    | '/learn/payments'
    | '/learn/security'
    | '/pay/$id'
    | '/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  PayIdRoute: typeof PayIdRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/security': {
      id: '/learn/security'
      path: '/security'
      fullPath: '/learn/security'
      preLoaderRoute: typeof LearnSecurityRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/payments': {
      id: '/learn/payments'
      path: '/payments'
      fullPath: '/learn/payments'
      preLoaderRoute: typeof LearnPaymentsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/invoice': {
      id: '/learn/invoice'
      path: '/invoice'
      fullPath: '/learn/invoice'
      preLoaderRoute: typeof LearnInvoiceRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/getting-started': {
      id: '/learn/getting-started'
      path: '/getting-started'
      fullPath: '/learn/getting-started'
      preLoaderRoute: typeof LearnGettingStartedRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/faq': {
      id: '/learn/faq'
      path: '/faq'
      fullPath: '/learn/faq'
      preLoaderRoute: typeof LearnFaqRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/business': {
      id: '/learn/business'
      path: '/business'
      fullPath: '/learn/business'
      preLoaderRoute: typeof LearnBusinessRouteImport
      parentRoute: typeof LearnRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LearnRouteChildren {
  LearnBusinessRoute: typeof LearnBusinessRoute
  LearnFaqRoute: typeof LearnFaqRoute
  LearnGettingStartedRoute: typeof LearnGettingStartedRoute
  LearnInvoiceRoute: typeof LearnInvoiceRoute
  LearnPaymentsRoute: typeof LearnPaymentsRoute
  LearnSecurityRoute: typeof LearnSecurityRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnBusinessRoute: LearnBusinessRoute,
  LearnFaqRoute: LearnFaqRoute,
  LearnGettingStartedRoute: LearnGettingStartedRoute,
  LearnInvoiceRoute: LearnInvoiceRoute,
  LearnPaymentsRoute: LearnPaymentsRoute,
  LearnSecurityRoute: LearnSecurityRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  PayIdRoute: PayIdRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
